import numpy as np
import torch
from sent2vec.vectorizer import Vectorizer
from sklearn.cluster import KMeans
sentences = ['drink water',
'eat meal or snack',
'brushing teeth',
'brushing hair',
'drop',
'pickup',
'throw',
'sitting down',
'standing up from sitting position',
'clapping',
'reading',
'writing',
'tear up paper',
'wear jacket',
'take off jacket',
'wear a shoe',
'take off a shoe',
'wear on glasses',
'take off glasses',
'put on a hat/cap',
'take off a hat/cap',
'cheer up',
'hand waving',
'kicking something',
'reach into pocket',
'one foot jumping',
'jump up',
'make a phone call or answer phone',
'playing with phone or tablet',
'typing on a keyboard',
'pointing to something with finger',
'taking a selfie',
'check time from watch',
'rub two hands together',
'nod head or bow',
'shake head',
'wipe face',
'salute',
'put the palms together',
'cross hands in front (say stop)',
'sneeze or cough',
'staggering',
'falling',
'touch head (headache)',
'touch chest (stomachache or heart pain)',
'touch back (backache)',
'touch neck (neckache)',
'nausea or vomiting condition',
'use a fan with hand or paper/feeling warm',
'punching or slapping other person',
'kicking other person',
'pushing other person',
'pat on back of other person',
'point finger at the other person',
'hugging other person',
'giving something to other person',
'touch other person\'s pocket',
'handshaking',
'walking towards each other',
'walking apart from each other']
vectorizer = Vectorizer()
vectorizer.run(sentences)
vectors = vectorizer.vectors
kmeans = KMeans(n_clusters=20, random_state=0, n_init="auto").fit(vectors)
labels = kmeans.labels_
for ind, item in enumerate(labels):
    print('A{}: {}'.format(ind, item))
