work_dir: /pfs/work7/workspace/scratch/fy2374-train/acmmm_and_aaai/aaai/checkpoints/CTRGCN_crossview_mm_mmd_r5
# feede2
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: /pfs/work7/workspace/scratch/fy2374-train/acmmm_and_aaai/aaai/ntu60_ctr_gcn_processed/NTU_CV.h5
  split: train
  run: 5
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args_unseen:
  data_path: /pfs/work7/workspace/scratch/fy2374-train/acmmm_and_aaai/aaai/ntu60_ctr_gcn_processed/NTU_CV.h5
  split: test_unseen
  run: 5
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False
test_feeder_args_seen:
  data_path: /pfs/work7/workspace/scratch/fy2374-train/acmmm_and_aaai/aaai/ntu60_ctr_gcn_processed/NTU_CV.h5
  split: test_seen
  run: 5
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False
# model
model: model.ctrgcn.Model
model_args:
  num_class: 40
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
model_args_upper:
  num_class: 40
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph_upper
  graph_args:
    labeling_mode: 'spatial'
model_args_lower:
  num_class: 40
  num_point: 10
  num_person: 2
  graph: graph.ntu_rgb_d.Graph_lower
  graph_args:
    labeling_mode: 'spatial'
#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55, 70]
warm_up_epoch: 5

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 100
nesterov: True
